fix: NetCDFIO
CliMA/SCAMPy pull request #104
Opened 2021-06-16 00:09 UTC by haakon-e

2021-06-16 00:14 UTC, haakon-e reviewed
remove these

2021-06-16 00:14 UTC, haakon-e commented on Cases.pxd
> +
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on Cases.pyx
> +        return StochasticBomex(paramlist)
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on Cases.pyx
> +
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on Turbulence_PrognosticTKE.pxd
> +
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on Turbulence_PrognosticTKE.pyx
> +
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on Turbulence_PrognosticTKE.pyx
> +        # Here, you can inject a stochastic closure.
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on Turbulence_PrognosticTKE.pyx
> +                    ## End: Haakon
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on generate_namelist.py
> +        namelist = StochasticBomex(namelist_defaults)
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on generate_namelist.py
> +
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on generate_paramlist.py
> +        paramlist = StochasticBomex(paramlist_defaults)
```suggestion
```

2021-06-16 00:14 UTC, haakon-e commented on generate_paramlist.py
> +
```suggestion
```

2021-06-16 08:02 UTC, trontrytel commented
Looks good to me. Could you also update the calls to `main1d` in tests? (Talking about all the `test_plot_...` semi automatic scripts inside the `tests/plots` folder and the tiny bit of unit tests that we have in `tests/unit` folder).  You can run all the tests by `py.test -s -v` inside the `tests` folder. Individual test can be run by `py.test -s -v plots/test_plot_TRMM_LBA.py` inside the `tests` folder.

I think there may be some inconsistency in prints syntax from python2 to python3. If we all agree I can just change it all to python3. I have been running scampy on python3 for a long time anyway.

2021-06-16 08:03 UTC, trontrytel requested changes
Aside from fixing the calls inside the tests, everything looks good

2021-06-17 00:53 UTC, yairchn approved these changes
LGTM

2021-06-17 17:20 UTC, merged