LES driven SCM
CliMA/SCAMPy pull request #105
Opened 2021-06-29 08:00 UTC by yairchn

This PR adds a case 'LES_driven_SCM' in which forcing, surface and radiation are read from LES stats file. 
As part of this addition I also added the files 'Radiation.pyx' and 'Radiation.pxd' where I located now the DYCOMS, TRMM radiation as well as the LES radiation of the new case. 
This sets the stage for adding RRTMG to SCMAPy as it would naturally be another class in Radiation.pyx.   

To run the new case one has to add a folder SCAMPy/LES_deriven_SCM/
and download from central:
1. the chosen LES 'stats' file from 
'/central/groups/esm/zhaoyi/GCMForcedLES/cfsite/07/HadGEM2-A/amip/'
2. the 'geolocation.nc' file that contains the latitude of the simulation from 
'/home/yairchn/geloc/geolocation.nc'

2021-06-29 22:32 UTC, szy21 commented on Cases.pyx
> +        self.Fo.apply_coriolis = True
I didn't apply Coriolis in the LES.

2021-06-30 10:53 UTC, trontrytel requested changes
LGTM! I left some minor comments. Mostly about a leftover code that should be deleted . I also wasnt sure about why `coriolis_force` inside one of the radiation modules.

2021-06-30 10:53 UTC, trontrytel commented on Cases.pxd
> +        RadiationBase Rad
rad radiation :)

2021-06-30 10:53 UTC, trontrytel commented on Cases.pyx
> +        # self.Fo.dTdt = np.zeros(Gr.nzg, dtype=np.double)
Are we ready to delete all the commented lines?

2021-06-30 10:53 UTC, trontrytel commented on Forcing.pyx
>          self.subsidence = np.zeros((self.Gr.nzg,), dtype=np.double, order='c')
Why do you need `TS` in the initialization?

2021-06-30 10:53 UTC, trontrytel commented on Forcing.pyx
> -#     def __init__(self):
CAn we delete this?

2021-06-30 10:53 UTC, trontrytel commented on Forcing.pyx
Should we delete this?

2021-06-30 10:53 UTC, trontrytel commented on Radiation.pyx
> +        return
Why Coriolis force should be inside radiation?

2021-06-30 10:54 UTC, trontrytel commented
Forgot to ask, did you run our tests to check if the old simulations are not changed?

2021-06-30 19:21 UTC, yairchn reviewed
I will push one more commit to fix some issues in the interpolation to the lowest level and some fixes to the tests/common.py where the rm function can't find the file to remove

2021-06-30 19:22 UTC, yairchn commented
> coriolis_force

that was a copy-paste mistake

2021-06-30 19:31 UTC, yairchn commented
> Forgot to ask, did you run our tests to check if the old simulations are not changed?

yes - all other cases are running an changes, especially including the DYCOMS and TRMM that use the new Radiation file

2021-07-01 17:42 UTC, szy21 commented on Cases.pyx
> +        self.Sur.qsurface = 1.0e-5
Do we need this?

2021-07-01 17:42 UTC, szy21 commented on Cases.pyx
> +        self.Sur.shf = 8.0e-3 * cpm_c(self.Sur.qsurface) * Ref.rho0[Gr.gw-1]
Do we need this?

2021-07-01 17:47 UTC, yairchn commented on Cases.pyx
> +        self.Sur.qsurface = 1.0e-5
these 'self.Sur.Gr = Gr' definitions are in every case, if I understand correctly the allow to access Gr under self in the class which is somewhat redundant with the function call having 'Grid Gr'
I would leave it for now, if we ever do a general cleanup it would be a good time to make this change

2021-07-01 17:55 UTC, szy21 commented on Cases.pyx
> +        self.Sur.qsurface = 1.0e-5
Oh I mean the `self.Sur.qsurface`, but yes we can clean it up later.

2021-07-01 17:55 UTC, szy21 commented on Cases.pyx
> +        self.Sur.shf = 8.0e-3 * cpm_c(self.Sur.qsurface) * Ref.rho0[Gr.gw-1]
Same here, I mean `self.Sur.shf`.

2021-07-01 18:24 UTC, szy21 reviewed
Thanks Yair! It looks good to me. I left a few more comments.

2021-07-01 18:24 UTC, szy21 commented on Forcing.pyx
> +        z_ = np.array(les_data.groups['profiles'].variables['z'])
Why not `z_half`? Or do you need `z_full` here? `z` might be a problem if the LES uses grid stretching.

2021-07-01 18:24 UTC, szy21 commented on Forcing.pyx
> +        latitude = lats[int(Gr.les_filename[29:31])-1]
Just a warning this might be a problem if the LES filename ever changes (e.g. the GCM used to generate the forcing changes). Maybe better to have a namelist input for the site number?

2021-07-01 18:24 UTC, szy21 commented on Forcing.pyx
> +        les_dtdt_nudge  = np.array(les_data['profiles'].variables['dtdt_nudge'])
It would be better to calculate the nudging tendency online in the future. Probably ok for now.

2021-07-01 18:24 UTC, szy21 commented on Grid.pyx
> +            z_top = np.max(les_data.groups['profiles'].variables['z'])
Same as before, this might be a problem if grid stretching is used in the LES. Do you want `z_half` or `z_full` here?

2021-07-01 18:24 UTC, szy21 commented on Radiation.pyx
> +        z_       = np.array(les_data.groups['profiles'].variables['z'])
Same as previous comments, this might be a problem if grid stretching is used in the LES.

2021-07-01 18:24 UTC, szy21 commented on ReferenceState.pyx
> +            z_les          = np.array(les_data.groups['profiles'].variables['z'])
Same as before. Consider using the following?
 `z_les = les_data.groups['reference'].variables['zp']`
 `z_les_half = les_data.groups['reference'].variables['zp_half']`

2021-07-01 23:42 UTC, yairchn commented on Forcing.pyx
> +        les_dtdt_nudge  = np.array(les_data['profiles'].variables['dtdt_nudge'])
but do we have the value to nudge to in the LES file? or should I be reading it from GCM ?

2021-07-01 23:51 UTC, szy21 commented on Forcing.pyx
> +        les_dtdt_nudge  = np.array(les_data['profiles'].variables['dtdt_nudge'])
Yes, just use the profile at t=0, same as what you did for u and v.

2021-07-13 12:47 UTC, yairchn commented on Cases.pxd
> +        RadiationBase Rad
I am not sure if you meant 'RadiationBase Rad' in line 16 - I added it in line 15 (above 'cpdef initialize_reference') is that ok?

2021-07-13 12:51 UTC, yairchn commented on Grid.pyx
> +            z_top = np.max(les_data.groups['profiles'].variables['z'])
'z_full' should it be 'zp_full'

2021-07-13 17:05 UTC, szy21 approved these changes

2021-07-13 17:20 UTC, trontrytel approved these changes

2021-07-15 02:15 UTC, merged